"""Independent Gazebo geometry checks for grasp and placement.

The default grasp must carry its proof lift through contact physics alone. An
optional detachable joint may only be enabled after these checks pass.
"""

from __future__ import annotations

from dataclasses import dataclass
import math
import threading
import time

from rclpy.node import Node
from ros_gz_interfaces.msg import Contacts
from tf2_msgs.msg import TFMessage
from rclpy.time import Time
from tf2_ros import Buffer, TransformException, TransformListener


@dataclass(frozen=True)
class Point3:
    """A Cartesian position in the configured factory frame."""

    x: float
    y: float
    z: float


@dataclass(frozen=True)
class Quaternion:
    """A unit quaternion used by the transport-independent geometry code."""

    x: float
    y: float
    z: float
    w: float


@dataclass(frozen=True)
class FrameTransform:
    """The pose of one child frame expressed in its parent frame."""

    parent_frame: str
    child_frame: str
    translation: Point3
    rotation: Quaternion


@dataclass(frozen=True)
class GeometryCheck:
    """One human-readable spatial acceptance result."""

    actual: Point3
    expected: Point3
    accepted: bool
    horizontal_error: float
    vertical_error: float

    def describe(self) -> str:
        verdict = "accepted" if self.accepted else "rejected"
        return (
            f"{verdict}: horizontal={self.horizontal_error:.3f} m, "
            f"vertical={self.vertical_error:.3f} m, "
            f"actual=({self.actual.x:.3f}, {self.actual.y:.3f}, "
            f"{self.actual.z:.3f}), "
            f"expected=({self.expected.x:.3f}, {self.expected.y:.3f}, "
            f"{self.expected.z:.3f})"
        )


@dataclass(frozen=True)
class AttachmentCheck:
    """Whether a workpiece kept its initial distance from the gripper link."""

    actual_distance: float
    reference_distance: float
    accepted: bool
    distance_error: float

    def describe(self) -> str:
        verdict = "accepted" if self.accepted else "rejected"
        return (
            f"{verdict}: gripper distance={self.actual_distance:.3f} m, "
            f"reference={self.reference_distance:.3f} m, "
            f"change={self.distance_error:.3f} m"
        )


@dataclass(frozen=True)
class OrientationCheck:
    """Whether the cylinder axis remains close to factory vertical."""

    tilt_degrees: float
    accepted: bool

    def describe(self) -> str:
        verdict = "accepted" if self.accepted else "rejected"
        return f"{verdict}: cylinder tilt={self.tilt_degrees:.1f} deg"


@dataclass(frozen=True)
class FingerContactCheck:
    """Whether both fingertips are touching the requested workpiece."""

    left: bool
    right: bool

    @property
    def accepted(self) -> bool:
        return self.left and self.right

    def describe(self) -> str:
        return f"left={self.left}, right={self.right}"


def check_finger_contact_times(
    left_time: float | None,
    right_time: float | None,
    *,
    now: float,
    max_age: float,
    received_after: float,
) -> FingerContactCheck:
    """Accept only fresh contacts generated by the current close command."""
    def is_current(sample_time: float | None) -> bool:
        return (
            sample_time is not None
            and sample_time >= received_after
            and now - sample_time <= max_age
        )

    return FingerContactCheck(
        left=is_current(left_time),
        right=is_current(right_time),
    )


def check_attachment_distance(
    actual_distance: float, reference_distance: float, max_error: float
) -> AttachmentCheck:
    error = abs(actual_distance - reference_distance)
    return AttachmentCheck(actual_distance, reference_distance, error <= max_error, error)


def check_upright(
    rotation: Quaternion, *, max_tilt_degrees: float
) -> OrientationCheck:
    """Measure the angle between the workpiece cylinder axis and world Z."""
    axis = _rotate(Point3(0.0, 0.0, 1.0), rotation)
    cosine = max(-1.0, min(1.0, abs(axis.z)))
    tilt = math.degrees(math.acos(cosine))
    return OrientationCheck(tilt, tilt <= max_tilt_degrees)


def contacts_include_part(message: Contacts, part_id: str) -> bool:
    """Return true only when a reported collision belongs to part_id."""
    if not part_id:
        raise ValueError("part_id must not be empty")

    def belongs_to_part(entity_name: str) -> bool:
        return (
            entity_name == part_id
            or entity_name.startswith(f"{part_id}::")
            or f"::{part_id}::" in entity_name
        )

    return any(
        belongs_to_part(contact.collision1.name)
        or belongs_to_part(contact.collision2.name)
        for contact in message.contacts
    )


def contact_pairs_for_part(
    message: Contacts, part_id: str
) -> tuple[tuple[str, str], ...]:
    """Return collision-name pairs involving one requested workpiece."""
    if not part_id:
        raise ValueError("part_id must not be empty")

    marker = f"{part_id}::"
    pairs = []
    for contact in message.contacts:
        pair = (contact.collision1.name, contact.collision2.name)
        if any(name == part_id or marker in name for name in pair):
            pairs.append(pair)
    return tuple(pairs)


def gripper_sides_touching_part(message: Contacts, part_id: str) -> set[str]:
    """Classify physical contacts between one part and the gripper sides."""
    if not part_id:
        raise ValueError("part_id must not be empty")

    part_marker = f"{part_id}::"
    sides: set[str] = set()
    for contact in message.contacts:
        names = (contact.collision1.name, contact.collision2.name)
        if not any(name == part_id or part_marker in name for name in names):
            continue
        for name in names:
            if "gripper_left_finger_tip_link" in name:
                sides.add("left")
            if "gripper_right_finger_tip_link" in name:
                sides.add("right")
    return sides


def check_position(
    actual: Point3,
    expected: Point3,
    *,
    max_horizontal_error: float,
    max_vertical_error: float,
) -> GeometryCheck:
    """Check XY and Z separately so tolerances have physical meaning."""
    horizontal = math.hypot(actual.x - expected.x, actual.y - expected.y)
    vertical = abs(actual.z - expected.z)
    return GeometryCheck(
        actual=actual,
        expected=expected,
        accepted=(
            horizontal <= max_horizontal_error
            and vertical <= max_vertical_error
        ),
        horizontal_error=horizontal,
        vertical_error=vertical,
    )


def resolve_frame_origin(
    transforms: tuple[FrameTransform, ...],
    child_frame: str,
    *,
    root_frames: tuple[str, ...],
) -> Point3 | None:
    """Resolve a child-frame origin by walking its transforms to a root."""
    by_child = {transform.child_frame: transform for transform in transforms}
    current_frame = child_frame
    position = Point3(0.0, 0.0, 0.0)
    visited: set[str] = set()

    while current_frame not in root_frames:
        if current_frame in visited:
            return None
        visited.add(current_frame)

        transform = by_child.get(current_frame)
        if transform is None:
            return None
        rotated = _rotate(position, transform.rotation)
        position = Point3(
            transform.translation.x + rotated.x,
            transform.translation.y + rotated.y,
            transform.translation.z + rotated.z,
        )
        current_frame = transform.parent_frame

    return position


def resolve_frame_rotation(
    transforms: tuple[FrameTransform, ...],
    child_frame: str,
    *,
    root_frames: tuple[str, ...],
) -> Quaternion | None:
    """Resolve a child-frame orientation by walking transforms to a root."""
    by_child = {transform.child_frame: transform for transform in transforms}
    current_frame = child_frame
    rotation = Quaternion(0.0, 0.0, 0.0, 1.0)
    visited: set[str] = set()

    while current_frame not in root_frames:
        if current_frame in visited:
            return None
        visited.add(current_frame)
        transform = by_child.get(current_frame)
        if transform is None:
            return None
        rotation = _multiply_quaternions(transform.rotation, rotation)
        current_frame = transform.parent_frame
    return rotation


def _multiply_quaternions(left: Quaternion, right: Quaternion) -> Quaternion:
    return Quaternion(
        left.w * right.x + left.x * right.w
        + left.y * right.z - left.z * right.y,
        left.w * right.y - left.x * right.z
        + left.y * right.w + left.z * right.x,
        left.w * right.z + left.x * right.y
        - left.y * right.x + left.z * right.w,
        left.w * right.w - left.x * right.x
        - left.y * right.y - left.z * right.z,
    )


def _rotate(point: Point3, quaternion: Quaternion) -> Point3:
    """Rotate a point with a normalized quaternion."""
    norm = math.sqrt(
        quaternion.x * quaternion.x
        + quaternion.y * quaternion.y
        + quaternion.z * quaternion.z
        + quaternion.w * quaternion.w
    )
    if norm < 1e-12:
        return point

    qx = quaternion.x / norm
    qy = quaternion.y / norm
    qz = quaternion.z / norm
    qw = quaternion.w / norm
    dot = qx * point.x + qy * point.y + qz * point.z
    cross_x = qy * point.z - qz * point.y
    cross_y = qz * point.x - qx * point.z
    cross_z = qx * point.y - qy * point.x
    scale = qw * qw - qx * qx - qy * qy - qz * qz
    return Point3(
        scale * point.x + 2.0 * dot * qx + 2.0 * qw * cross_x,
        scale * point.y + 2.0 * dot * qy + 2.0 * qw * cross_y,
        scale * point.z + 2.0 * dot * qz + 2.0 * qw * cross_z,
    )

def transform_point(transform: FrameTransform, point: Point3) -> Point3:
    """Express a point in the parent frame of a rigid transform."""
    rotated = _rotate(point, transform.rotation)
    return Point3(
        transform.translation.x + rotated.x,
        transform.translation.y + rotated.y,
        transform.translation.z + rotated.z,
    )

def point_correction_in_parent(
    actual: Point3, desired: Point3, parent_rotation: Quaternion
) -> Point3:
    """Return an XYZ correction expressed in the moving parent frame."""
    difference = Point3(
        desired.x - actual.x,
        desired.y - actual.y,
        desired.z - actual.z,
    )
    inverse_rotation = Quaternion(
        -parent_rotation.x,
        -parent_rotation.y,
        -parent_rotation.z,
        parent_rotation.w,
    )
    return _rotate(difference, inverse_rotation)

class GazeboTruthObserver:
    """Track independent Gazebo truth for workpieces, gripper, and robot."""

    def __init__(
        self,
        node: Node,
        part_ids: tuple[str, ...],
        *,
        pose_frame: str = "map",
        max_sample_age: float = 1.0,
    ) -> None:
        self._node = node
        self._pose_frame = pose_frame
        self._max_sample_age = max_sample_age
        self._poses: dict[str, tuple[Point3, float]] = {}
        self._orientations: dict[str, tuple[Quaternion, float]] = {}
        self._pose_lock = threading.Lock()
        self._finger_contact_times: dict[str, dict[str, float]] = {
            "left": {},
            "right": {},
        }
        self._physical_fingertips: dict[str, tuple[Point3, float]] = {}
        self._physical_pads: dict[str, tuple[Point3, float]] = {}
        self._part_contact_pairs: dict[
            str, dict[tuple[str, str], float]
        ] = {part_id: {} for part_id in part_ids}
        self._part_ids = part_ids
        # These are resolved directly from Gazebo's physical link pose graph.
        # Do not combine a Gazebo model origin with a ROS TF chain: fixed-joint
        # reduction makes those origins differ by a physics-engine-dependent
        # offset.
        self._base_link_transform: (
            tuple[FrameTransform, float] | None
        ) = None
        self._physical_grasp_anchor: tuple[Point3, float] | None = None
        self._tf_buffer = Buffer()
        self._tf_listener = TransformListener(self._tf_buffer, node)
        self._robot_subscription = node.create_subscription(
            TFMessage, "/factory/robot/pose", self._remember_robot_pose_graph, 5
        )
        self._subscriptions = [
            node.create_subscription(
                TFMessage,
                f"/factory/workpieces/{part_id}/pose",
                lambda message, current=part_id: self._remember_pose_graph(
                    current, message
                ),
                5,
            )
            for part_id in part_ids
        ]
        self._workpiece_contact_subscription = node.create_subscription(
            Contacts,
            "/factory/workpieces/contacts",
            self._remember_workpiece_contacts,
            10,
        )

    def grasp_correction_in_base(
        self,
        part_id: str,
        target: Point3,
        target_frame: str,
        *,
        timeout_sec: float,
    ) -> Point3:
        """Correct a configured target before the gripper can touch the part."""
        deadline = time.monotonic() + timeout_sec
        while time.monotonic() < deadline:
            part_position = self._fresh_part_position(part_id)
            target_in_factory = self._expected_in_factory(target, target_frame)
            with self._pose_lock:
                base_sample = self._base_link_transform
            if (
                part_position is None
                or target_in_factory is None
                or base_sample is None
            ):
                time.sleep(0.05)
                continue

            base_transform, received_at = base_sample
            if time.monotonic() - received_at > self._max_sample_age:
                time.sleep(0.05)
                continue
            return point_correction_in_parent(
                target_in_factory,
                part_position,
                base_transform.rotation,
            )

        raise RuntimeError(
            f"cannot calibrate {part_id} from fresh simulator geometry"
        )

    def part_target_correction_in_base(
        self,
        part_id: str,
        target: Point3,
        target_frame: str,
        *,
        timeout_sec: float,
    ) -> Point3:
        """Return the base-frame motion that centers a held part on a target.

        This uses Gazebo's workpiece and base poses, rather than assuming the
        cylinder stayed at the nominal attached-object offset in MoveIt.
        """
        deadline = time.monotonic() + timeout_sec
        while time.monotonic() < deadline:
            part_position = self._fresh_part_position(part_id)
            target_in_factory = self._expected_in_factory(
                target, target_frame
            )
            with self._pose_lock:
                base_sample = self._base_link_transform
            if (
                part_position is None
                or target_in_factory is None
                or base_sample is None
            ):
                time.sleep(0.05)
                continue

            base_transform, received_at = base_sample
            if time.monotonic() - received_at > self._max_sample_age:
                time.sleep(0.05)
                continue
            return point_correction_in_parent(
                part_position,
                target_in_factory,
                base_transform.rotation,
            )

        raise RuntimeError(
            f"cannot align held {part_id} with fresh simulator geometry"
        )

    def anchor_correction_from_part_in_base(
        self,
        part_id: str,
        expected_anchor_offset: Point3,
        *,
        timeout_sec: float,
    ) -> Point3:
        """Measure a safe pre-contact correction from Gazebo link truth."""
        deadline = time.monotonic() + timeout_sec
        while time.monotonic() < deadline:
            part_position = self._fresh_part_position(part_id)
            with self._pose_lock:
                anchor_sample = self._physical_grasp_anchor
                base_sample = self._base_link_transform
            if (
                part_position is None
                or anchor_sample is None
                or base_sample is None
            ):
                time.sleep(0.05)
                continue

            anchor, anchor_received_at = anchor_sample
            base_transform, base_received_at = base_sample
            now = time.monotonic()
            if (
                now - anchor_received_at > self._max_sample_age
                or now - base_received_at > self._max_sample_age
            ):
                time.sleep(0.05)
                continue

            offset_in_factory = _rotate(
                expected_anchor_offset, base_transform.rotation
            )
            desired_anchor = Point3(
                part_position.x + offset_in_factory.x,
                part_position.y + offset_in_factory.y,
                part_position.z + offset_in_factory.z,
            )
            return point_correction_in_parent(
                anchor, desired_anchor, base_transform.rotation
            )

        raise RuntimeError(
            f"cannot align the physical grasp anchor for {part_id}"
        )

    def check_grasp(
        self,
        part_id: str,
        *,
        max_horizontal_error: float,
        expected_anchor_offset: Point3,
        max_vertical_error: float,
        timeout_sec: float,
    ) -> GeometryCheck:
        """Verify the Gazebo gripper anchor is physically at the part."""
        deadline = time.monotonic() + timeout_sec
        last_check: GeometryCheck | None = None

        while time.monotonic() < deadline:
            pair = self._fresh_attachment_pair(part_id)
            if pair is None:
                time.sleep(0.05)
                continue

            part_position, anchor_position = pair
            offset_in_factory = self._base_offset_in_factory(
                expected_anchor_offset
            )
            if offset_in_factory is None:
                time.sleep(0.05)
                continue
            expected_anchor = Point3(
                part_position.x + offset_in_factory.x,
                part_position.y + offset_in_factory.y,
                part_position.z + offset_in_factory.z,
            )
            check = check_position(
                anchor_position,
                expected_anchor,
                max_horizontal_error=max_horizontal_error,
                max_vertical_error=max_vertical_error,
            )
            if check.accepted:
                return check
            last_check = check
            time.sleep(0.05)

        if last_check is not None:
            return last_check

        raise RuntimeError(
            f"cannot verify {part_id} against the Gazebo gripper anchor"
        )

    def check_part_at_target(
        self,
        part_id: str,
        expected: Point3,
        expected_frame: str,
        *,
        max_horizontal_error: float,
        max_vertical_error: float,
        timeout_sec: float,
        received_after: float | None = None,
    ) -> GeometryCheck:
        """Wait for a fresh sample and verify a placement zone."""
        deadline = time.monotonic() + timeout_sec
        while time.monotonic() < deadline:
            expected_in_factory = self._expected_in_factory(
                expected, expected_frame
            )
            if expected_in_factory is None:
                time.sleep(0.05)
                continue
            sample = self._fresh_part_sample(part_id)
            if sample is not None:
                position, received_at = sample
                if received_after is None or received_at >= received_after:
                    return check_position(
                        position,
                        expected_in_factory,
                        max_horizontal_error=max_horizontal_error,
                        max_vertical_error=max_vertical_error,
                    )
            time.sleep(0.05)

        raise RuntimeError(f"no fresh pose received for {part_id}")

    def check_part_upright(
        self,
        part_id: str,
        *,
        max_tilt_degrees: float,
        timeout_sec: float,
    ) -> OrientationCheck:
        """Wait for fresh Gazebo orientation and reject a tilted cylinder."""
        deadline = time.monotonic() + timeout_sec
        while time.monotonic() < deadline:
            sample = self._fresh_part_orientation(part_id)
            if sample is not None:
                return check_upright(
                    sample, max_tilt_degrees=max_tilt_degrees
                )
            time.sleep(0.05)
        raise RuntimeError(f"no fresh orientation received for {part_id}")

    def begin_contact_window(self, part_id: str) -> float:
        """Forget old contacts and mark the start of one close attempt."""
        if part_id not in self._part_ids:
            raise ValueError(f"unknown workpiece: {part_id}")
        with self._pose_lock:
            started_at = time.monotonic()
            self._finger_contact_times["left"].pop(part_id, None)
            self._finger_contact_times["right"].pop(part_id, None)
        return started_at

    def check_two_finger_contact(
        self,
        part_id: str,
        *,
        timeout_sec: float,
        received_after: float,
    ) -> FingerContactCheck:
        """Wait for both fingertips to contact the part after closing starts."""
        deadline = time.monotonic() + timeout_sec
        last = FingerContactCheck(False, False)

        while time.monotonic() < deadline:
            now = time.monotonic()
            with self._pose_lock:
                left_time = self._finger_contact_times["left"].get(part_id)
                right_time = self._finger_contact_times["right"].get(part_id)
            last = check_finger_contact_times(
                left_time,
                right_time,
                now=now,
                max_age=self._max_sample_age,
                received_after=received_after,
            )
            if last.accepted:
                return last
            time.sleep(0.02)

        return last

    def recent_two_finger_contact(self, part_id: str) -> FingerContactCheck:
        """Return the latest non-blocking bilateral-contact observation."""
        now = time.monotonic()
        with self._pose_lock:
            left_time = self._finger_contact_times["left"].get(part_id)
            right_time = self._finger_contact_times["right"].get(part_id)
        return check_finger_contact_times(
            left_time,
            right_time,
            now=now,
            max_age=self._max_sample_age,
            received_after=0.0,
        )

    def attachment_snapshot(
        self, part_id: str
    ) -> tuple[Point3, Point3, float] | None:
        """Return a non-blocking part, anchor and distance snapshot."""
        pair = self._fresh_attachment_pair(part_id)
        if pair is None:
            return None
        part, anchor = pair
        distance = math.dist(
            (part.x, part.y, part.z), (anchor.x, anchor.y, anchor.z)
        )
        return part, anchor, distance

    def _remember_workpiece_contacts(self, message: Contacts) -> None:
        """Record the gripper side and raw collision pair for diagnostics."""
        received_at = time.monotonic()
        with self._pose_lock:
            for part_id in self._part_ids:
                self._remember_contact_pairs(part_id, message, received_at)
                for side in gripper_sides_touching_part(message, part_id):
                    self._finger_contact_times[side][part_id] = received_at

    def _remember_contact_pairs(
        self, part_id: str, message: Contacts, received_at: float
    ) -> None:
        for pair in contact_pairs_for_part(message, part_id):
            self._part_contact_pairs[part_id][pair] = received_at

    def recent_contact_summary(
        self, part_id: str, *, max_age: float = 2.0
    ) -> str:
        """Describe recent Gazebo collision pairs involving part_id."""
        now = time.monotonic()
        with self._pose_lock:
            recent = [
                pair
                for pair, received_at in self._part_contact_pairs[part_id].items()
                if now - received_at <= max_age
            ]
        if not recent:
            return "contacts=none"
        names = sorted(" <-> ".join(pair) for pair in recent)
        return "contacts=" + "; ".join(names)

    def point_in_base(
        self,
        source_frame: str,
        point: Point3,
        *,
        timeout_sec: float,
    ) -> Point3:
        """Transform a calibrated station point into the current base frame."""
        deadline = time.monotonic() + timeout_sec
        while time.monotonic() < deadline:
            try:
                message = self._tf_buffer.lookup_transform(
                    "base_link", source_frame, Time()
                )
            except TransformException:
                time.sleep(0.02)
                continue

            translation = message.transform.translation
            rotation = message.transform.rotation
            transform = FrameTransform(
                parent_frame="base_link",
                child_frame=source_frame,
                translation=Point3(
                    translation.x, translation.y, translation.z
                ),
                rotation=Quaternion(
                    rotation.x, rotation.y, rotation.z, rotation.w
                ),
            )
            return transform_point(transform, point)
        raise RuntimeError(f"no current base_link to {source_frame} transform")

    def current_tcp_in_base(
        self, *, timeout_sec: float
    ) -> tuple[Point3, Quaternion]:
        """Return the latest joint-state-derived gripper TCP pose."""
        deadline = time.monotonic() + timeout_sec
        while time.monotonic() < deadline:
            try:
                transform = self._tf_buffer.lookup_transform(
                    "base_link", "gripper_tcp", Time()
                )
            except TransformException:
                time.sleep(0.02)
                continue
            translation = transform.transform.translation
            rotation = transform.transform.rotation
            return (
                Point3(translation.x, translation.y, translation.z),
                Quaternion(rotation.x, rotation.y, rotation.z, rotation.w),
            )
        raise RuntimeError("no current base_link to gripper_tcp transform")

    def kinematic_pad_positions_in_base(
        self, *, timeout_sec: float
    ) -> tuple[Point3, Point3]:
        """Return joint-state-derived finger centers expressed in base_link."""
        deadline = time.monotonic() + timeout_sec
        while time.monotonic() < deadline:
            positions = []
            for side in ("left", "right"):
                try:
                    transform = self._tf_buffer.lookup_transform(
                        "base_link", f"gripper_{side}_finger_tip_link", Time()
                    )
                except TransformException:
                    break
                translation = transform.transform.translation
                positions.append(
                    Point3(translation.x, translation.y, translation.z)
                )
            if len(positions) == 2:
                return positions[0], positions[1]
            time.sleep(0.02)
        raise RuntimeError("no current base_link to gripper finger transforms")

    def physical_pad_positions(
        self, *, timeout_sec: float
    ) -> tuple[Point3, Point3]:
        """Return fresh Gazebo positions for both physical finger bodies.

        The method name remains as a compatibility boundary for diagnostics.
        """
        deadline = time.monotonic() + timeout_sec
        while time.monotonic() < deadline:
            with self._pose_lock:
                left = self._physical_pads.get("left")
                right = self._physical_pads.get("right")
            now = time.monotonic()
            if (
                left is not None
                and right is not None
                and now - left[1] <= self._max_sample_age
                and now - right[1] <= self._max_sample_age
            ):
                return left[0], right[0]
            time.sleep(0.02)
        raise RuntimeError("no fresh Gazebo pad poses received")

    def physical_fingertip_positions(
        self, *, timeout_sec: float
    ) -> tuple[Point3, Point3]:
        """Return fresh Gazebo positions for the left and right fingertip links."""
        deadline = time.monotonic() + timeout_sec
        while time.monotonic() < deadline:
            with self._pose_lock:
                left = self._physical_fingertips.get("left")
                right = self._physical_fingertips.get("right")
            now = time.monotonic()
            if (
                left is not None
                and right is not None
                and now - left[1] <= self._max_sample_age
                and now - right[1] <= self._max_sample_age
            ):
                return left[0], right[0]
            time.sleep(0.02)
        raise RuntimeError("no fresh Gazebo fingertip poses received")

    def current_part_position(
        self,
        part_id: str,
        *,
        timeout_sec: float,
        received_after: float | None = None,
    ) -> Point3:
        """Return a fresh Gazebo position for one physical workpiece."""
        deadline = time.monotonic() + timeout_sec
        while time.monotonic() < deadline:
            sample = self._fresh_part_sample(part_id)
            if sample is not None:
                position, received_at = sample
                if received_after is None or received_at >= received_after:
                    return position
            time.sleep(0.02)
        raise RuntimeError(f"no fresh pose received for {part_id}")

    def capture_attachment_distance(
        self, part_id: str, *, timeout_sec: float
    ) -> float:
        """Measure the physical part-to-gripper distance after attachment."""
        deadline = time.monotonic() + timeout_sec
        while time.monotonic() < deadline:
            pair = self._fresh_attachment_pair(part_id)
            if pair is not None:
                part, gripper = pair
                self._node.get_logger().info(
                    f"Attachment endpoints for {part_id}: "
                    f"part=({part.x:.3f}, {part.y:.3f}, {part.z:.3f}), "
                    f"anchor=({gripper.x:.3f}, {gripper.y:.3f}, {gripper.z:.3f})"
                )
                return math.dist(
                    (part.x, part.y, part.z),
                    (gripper.x, gripper.y, gripper.z),
                )
            time.sleep(0.05)
        raise RuntimeError(
            f"cannot measure {part_id} relative to the Gazebo gripper link"
        )

    def check_attachment(
        self,
        part_id: str,
        reference_distance: float,
        *,
        max_error: float,
        timeout_sec: float,
    ) -> AttachmentCheck:
        actual = self.capture_attachment_distance(
            part_id, timeout_sec=timeout_sec
        )
        return check_attachment_distance(actual, reference_distance, max_error)

    def _fresh_attachment_pair(
        self, part_id: str
    ) -> tuple[Point3, Point3] | None:
        """Return part and grasp-anchor positions from Gazebo link truth."""
        part = self._fresh_part_position(part_id)
        with self._pose_lock:
            anchor_sample = self._physical_grasp_anchor
        if part is None or anchor_sample is None:
            return None
        anchor, received_at = anchor_sample
        if time.monotonic() - received_at > self._max_sample_age:
            return None
        return part, anchor


    def _remember_robot_pose_graph(self, message: TFMessage) -> None:
        transforms = self._convert_transforms(message)
        base_frame = next(
            (
                transform.child_frame
                for transform in transforms
                if transform.child_frame in ("base_link", "base_footprint")
                or transform.child_frame.endswith(
                    ("::base_link", "/base_link", "::base_footprint", "/base_footprint")
                )
            ),
            None,
        )
        anchor_frame = next(
            (
                transform.child_frame
                for transform in transforms
                if transform.child_frame.endswith("gripper_grasp_anchor")
            ),
            None,
        )
        base_transform = None
        if base_frame is not None:
            base_position = self._resolve_in_factory(transforms, base_frame)
            base_rotation = resolve_frame_rotation(
                transforms,
                base_frame,
                root_frames=(self._pose_frame, "world", "multi_machine_factory"),
            )
            if base_position is not None and base_rotation is not None:
                physical_base = FrameTransform(
                    parent_frame=self._pose_frame,
                    child_frame=base_frame,
                    translation=base_position,
                    rotation=base_rotation,
                )
                if base_frame.endswith("base_footprint"):
                    # base_link is fixed 0.34 m above base_footprint in the
                    # robot URDF. Gazebo publishes the physical footprint and
                    # lumps the massless base_link fixed joint.
                    base_position = transform_point(
                        physical_base, Point3(0.0, 0.0, 0.34)
                    )
                base_transform = FrameTransform(
                    parent_frame=self._pose_frame,
                    child_frame="base_link",
                    translation=base_position,
                    rotation=base_rotation,
                )
        anchor_position = (
            None
            if anchor_frame is None
            else self._resolve_in_factory(transforms, anchor_frame)
        )
        received_at = time.monotonic()
        fingertip_positions = {}
        for side in ("left", "right"):
            suffix = f"gripper_{side}_finger_tip_link"
            frame = next(
                (
                    transform.child_frame
                    for transform in transforms
                    if transform.child_frame.endswith(suffix)
                ),
                None,
            )
            if frame is not None:
                position = self._resolve_in_factory(transforms, frame)
                if position is not None:
                    fingertip_positions[side] = position

        with self._pose_lock:
            if base_transform is not None:
                self._base_link_transform = (base_transform, received_at)
            if anchor_position is not None:
                self._physical_grasp_anchor = (anchor_position, received_at)
            for side, position in fingertip_positions.items():
                self._physical_fingertips[side] = (position, received_at)
            for side, position in fingertip_positions.items():
                self._physical_pads[side] = (position, received_at)


    def _remember_pose_graph(
        self, part_id: str, message: TFMessage
    ) -> None:
        transforms = self._convert_transforms(message)
        link_frame = next(
            (
                transform.child_frame
                for transform in transforms
                if transform.child_frame == f"{part_id}::part"
                or transform.child_frame == f"{part_id}/part"
            ),
            None,
        )
        if link_frame is None:
            return

        position = self._resolve_in_factory(transforms, link_frame)
        orientation = resolve_frame_rotation(
            transforms,
            link_frame,
            root_frames=(self._pose_frame, "world", "multi_machine_factory"),
        )
        if position is None or orientation is None:
            return

        received_at = time.monotonic()
        with self._pose_lock:
            self._poses[part_id] = (position, received_at)
            self._orientations[part_id] = (orientation, received_at)

    @staticmethod
    def _convert_transforms(message: TFMessage) -> tuple[FrameTransform, ...]:
        return tuple(
            FrameTransform(
                parent_frame=transform.header.frame_id,
                child_frame=transform.child_frame_id,
                translation=Point3(
                    transform.transform.translation.x,
                    transform.transform.translation.y,
                    transform.transform.translation.z,
                ),
                rotation=Quaternion(
                    transform.transform.rotation.x,
                    transform.transform.rotation.y,
                    transform.transform.rotation.z,
                    transform.transform.rotation.w,
                ),
            )
            for transform in message.transforms
        )

    def _resolve_in_factory(
        self, transforms: tuple[FrameTransform, ...], child_frame: str
    ) -> Point3 | None:
        return resolve_frame_origin(
            transforms,
            child_frame,
            root_frames=(self._pose_frame, "world", "multi_machine_factory"),
        )

    def _base_offset_in_factory(self, offset: Point3) -> Point3 | None:
        """Rotate a base-link vector into the simulator truth frame."""
        with self._pose_lock:
            base_sample = self._base_link_transform
        if base_sample is None:
            return None
        base_transform, received_at = base_sample
        if time.monotonic() - received_at > self._max_sample_age:
            return None
        return _rotate(offset, base_transform.rotation)

    def _expected_in_factory(
        self, expected: Point3, expected_frame: str
    ) -> Point3 | None:
        if expected_frame == self._pose_frame:
            return expected
        if expected_frame != "base_link":
            raise RuntimeError(
                f"unsupported placement frame: {expected_frame}"
            )

        with self._pose_lock:
            base_sample = self._base_link_transform
        if base_sample is None:
            return None
        base_transform, received_at = base_sample
        if time.monotonic() - received_at > self._max_sample_age:
            return None
        return transform_point(base_transform, expected)

    def _fresh_part_position(self, part_id: str) -> Point3 | None:
        sample = self._fresh_part_sample(part_id)
        return None if sample is None else sample[0]

    def _fresh_part_sample(
        self, part_id: str
    ) -> tuple[Point3, float] | None:
        with self._pose_lock:
            sample = self._poses.get(part_id)
        if sample is None:
            return None
        if time.monotonic() - sample[1] > self._max_sample_age:
            return None
        return sample

    def _fresh_part_orientation(self, part_id: str) -> Quaternion | None:
        with self._pose_lock:
            sample = self._orientations.get(part_id)
        if sample is None:
            return None
        if time.monotonic() - sample[1] > self._max_sample_age:
            return None
        return sample[0]
