- ros_topic_name: /clock
  gz_topic_name: /clock
  ros_type_name: rosgraph_msgs/msg/Clock
  gz_type_name: gz.msgs.Clock
  direction: GZ_TO_ROS
- ros_topic_name: /scan
  gz_topic_name: /scan
  ros_type_name: sensor_msgs/msg/LaserScan
  gz_type_name: gz.msgs.LaserScan
  direction: GZ_TO_ROS
- ros_topic_name: /imu/data
  gz_topic_name: /imu/data
  ros_type_name: sensor_msgs/msg/Imu
  gz_type_name: gz.msgs.IMU
  direction: GZ_TO_ROS
- ros_topic_name: /ground_truth/odom
  gz_topic_name: /model/factory_robot/odometry
  ros_type_name: nav_msgs/msg/Odometry
  gz_type_name: gz.msgs.Odometry
  direction: GZ_TO_ROS
- ros_topic_name: /factory/robot/pose
  gz_topic_name: /model/factory_robot/pose
  ros_type_name: tf2_msgs/msg/TFMessage
  gz_type_name: gz.msgs.Pose_V
  direction: GZ_TO_ROS
- ros_topic_name: /camera/image_raw
  gz_topic_name: /camera/image
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS
- ros_topic_name: /camera/depth/image_raw
  gz_topic_name: /camera/depth_image
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS
- ros_topic_name: /camera/camera_info
  gz_topic_name: /camera/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: gz.msgs.CameraInfo
  direction: GZ_TO_ROS
- ros_topic_name: /camera_aux/image_raw
  gz_topic_name: /camera_aux/image
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS
- ros_topic_name: /camera_aux/depth/image_raw
  gz_topic_name: /camera_aux/depth_image
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS
- ros_topic_name: /camera_aux/camera_info
  gz_topic_name: /camera_aux/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: gz.msgs.CameraInfo
  direction: GZ_TO_ROS
- ros_topic_name: /tag_camera/image_raw
  gz_topic_name: /tag_camera
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS
- ros_topic_name: /tag_camera/camera_info
  gz_topic_name: /camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: gz.msgs.CameraInfo
  direction: GZ_TO_ROS
- ros_topic_name: /machine_1/door_position_cmd
  gz_topic_name: /model/machine_1/joint/sliding_door_joint/0/cmd_pos
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
- ros_topic_name: /machine_2/door_position_cmd
  gz_topic_name: /model/machine_2/joint/sliding_door_joint/0/cmd_pos
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
- ros_topic_name: /machine_3/door_position_cmd
  gz_topic_name: /model/machine_3/joint/sliding_door_joint/0/cmd_pos
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
- ros_topic_name: /machine_1/door_joint_state
  gz_topic_name: /world/multi_machine_factory/model/machine_1/joint_state
  ros_type_name: sensor_msgs/msg/JointState
  gz_type_name: gz.msgs.Model
  direction: GZ_TO_ROS
- ros_topic_name: /machine_2/door_joint_state
  gz_topic_name: /world/multi_machine_factory/model/machine_2/joint_state
  ros_type_name: sensor_msgs/msg/JointState
  gz_type_name: gz.msgs.Model
  direction: GZ_TO_ROS
- ros_topic_name: /machine_3/door_joint_state
  gz_topic_name: /world/multi_machine_factory/model/machine_3/joint_state
  ros_type_name: sensor_msgs/msg/JointState
  gz_type_name: gz.msgs.Model
  direction: GZ_TO_ROS
- ros_topic_name: /factory/workpieces/raw_part_1/pose
  gz_topic_name: /model/raw_part_1/pose
  ros_type_name: tf2_msgs/msg/TFMessage
  gz_type_name: gz.msgs.Pose_V
  direction: GZ_TO_ROS
- ros_topic_name: /factory/workpieces/raw_part_2/pose
  gz_topic_name: /model/raw_part_2/pose
  ros_type_name: tf2_msgs/msg/TFMessage
  gz_type_name: gz.msgs.Pose_V
  direction: GZ_TO_ROS
- ros_topic_name: /factory/workpieces/raw_part_3/pose
  gz_topic_name: /model/raw_part_3/pose
  ros_type_name: tf2_msgs/msg/TFMessage
  gz_type_name: gz.msgs.Pose_V
  direction: GZ_TO_ROS
- ros_topic_name: /factory/charging/contacts
  gz_topic_name: /factory/charging/contacts
  ros_type_name: ros_gz_interfaces/msg/Contacts
  gz_type_name: gz.msgs.Contacts
  direction: GZ_TO_ROS
- ros_topic_name: /factory/workpieces/contacts
  gz_topic_name: /factory/workpieces/contacts
  ros_type_name: ros_gz_interfaces/msg/Contacts
  gz_type_name: gz.msgs.Contacts
  direction: GZ_TO_ROS
- ros_topic_name: /factory/cnc/contacts
  gz_topic_name: /factory/cnc/contacts
  ros_type_name: ros_gz_interfaces/msg/Contacts
  gz_type_name: gz.msgs.Contacts
  direction: GZ_TO_ROS
- ros_topic_name: /factory/fixture/raw_part_1/attach
  gz_topic_name: /factory/fixture/raw_part_1/attach
  ros_type_name: std_msgs/msg/Empty
  gz_type_name: gz.msgs.Empty
  direction: ROS_TO_GZ
- ros_topic_name: /factory/fixture/raw_part_1/detach
  gz_topic_name: /factory/fixture/raw_part_1/detach
  ros_type_name: std_msgs/msg/Empty
  gz_type_name: gz.msgs.Empty
  direction: ROS_TO_GZ
- ros_topic_name: /factory/fixture/raw_part_1/attached
  gz_topic_name: /factory/fixture/raw_part_1/attached
  ros_type_name: std_msgs/msg/String
  gz_type_name: gz.msgs.StringMsg
  direction: GZ_TO_ROS
- ros_topic_name: /factory/fixture/raw_part_2/attach
  gz_topic_name: /factory/fixture/raw_part_2/attach
  ros_type_name: std_msgs/msg/Empty
  gz_type_name: gz.msgs.Empty
  direction: ROS_TO_GZ
- ros_topic_name: /factory/fixture/raw_part_2/detach
  gz_topic_name: /factory/fixture/raw_part_2/detach
  ros_type_name: std_msgs/msg/Empty
  gz_type_name: gz.msgs.Empty
  direction: ROS_TO_GZ
- ros_topic_name: /factory/fixture/raw_part_2/attached
  gz_topic_name: /factory/fixture/raw_part_2/attached
  ros_type_name: std_msgs/msg/String
  gz_type_name: gz.msgs.StringMsg
  direction: GZ_TO_ROS
- ros_topic_name: /factory/fixture/raw_part_3/attach
  gz_topic_name: /factory/fixture/raw_part_3/attach
  ros_type_name: std_msgs/msg/Empty
  gz_type_name: gz.msgs.Empty
  direction: ROS_TO_GZ
- ros_topic_name: /factory/fixture/raw_part_3/detach
  gz_topic_name: /factory/fixture/raw_part_3/detach
  ros_type_name: std_msgs/msg/Empty
  gz_type_name: gz.msgs.Empty
  direction: ROS_TO_GZ
- ros_topic_name: /factory/fixture/raw_part_3/attached
  gz_topic_name: /factory/fixture/raw_part_3/attached
  ros_type_name: std_msgs/msg/String
  gz_type_name: gz.msgs.StringMsg
  direction: GZ_TO_ROS
- ros_topic_name: /factory/fixture/raw_part_4/attach
  gz_topic_name: /factory/fixture/raw_part_4/attach
  ros_type_name: std_msgs/msg/Empty
  gz_type_name: gz.msgs.Empty
  direction: ROS_TO_GZ
- ros_topic_name: /factory/fixture/raw_part_4/detach
  gz_topic_name: /factory/fixture/raw_part_4/detach
  ros_type_name: std_msgs/msg/Empty
  gz_type_name: gz.msgs.Empty
  direction: ROS_TO_GZ
- ros_topic_name: /factory/fixture/raw_part_4/attached
  gz_topic_name: /factory/fixture/raw_part_4/attached
  ros_type_name: std_msgs/msg/String
  gz_type_name: gz.msgs.StringMsg
  direction: GZ_TO_ROS
- ros_topic_name: /factory/fixture/raw_part_5/attach
  gz_topic_name: /factory/fixture/raw_part_5/attach
  ros_type_name: std_msgs/msg/Empty
  gz_type_name: gz.msgs.Empty
  direction: ROS_TO_GZ
- ros_topic_name: /factory/fixture/raw_part_5/detach
  gz_topic_name: /factory/fixture/raw_part_5/detach
  ros_type_name: std_msgs/msg/Empty
  gz_type_name: gz.msgs.Empty
  direction: ROS_TO_GZ
- ros_topic_name: /factory/fixture/raw_part_5/attached
  gz_topic_name: /factory/fixture/raw_part_5/attached
  ros_type_name: std_msgs/msg/String
  gz_type_name: gz.msgs.StringMsg
  direction: GZ_TO_ROS
- ros_topic_name: /factory/fixture/raw_part_6/attach
  gz_topic_name: /factory/fixture/raw_part_6/attach
  ros_type_name: std_msgs/msg/Empty
  gz_type_name: gz.msgs.Empty
  direction: ROS_TO_GZ
- ros_topic_name: /factory/fixture/raw_part_6/detach
  gz_topic_name: /factory/fixture/raw_part_6/detach
  ros_type_name: std_msgs/msg/Empty
  gz_type_name: gz.msgs.Empty
  direction: ROS_TO_GZ
- ros_topic_name: /factory/fixture/raw_part_6/attached
  gz_topic_name: /factory/fixture/raw_part_6/attached
  ros_type_name: std_msgs/msg/String
  gz_type_name: gz.msgs.StringMsg
  direction: GZ_TO_ROS
