#!/usr/bin/env python3
"""Generate the simulation occupancy map from the Gazebo scene geometry."""

from __future__ import annotations

import argparse
import math
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from pathlib import Path

RESOLUTION = 0.05
ORIGIN_X = -7.0
ORIGIN_Y = -5.0
WIDTH = 280
HEIGHT = 200
SCAN_HEIGHT = 0.475
FREE = 254
OCCUPIED = 0


@dataclass(frozen=True)
class Pose:
    x: float = 0.0
    y: float = 0.0
    z: float = 0.0
    yaw: float = 0.0


def parse_pose(text: str | None) -> Pose:
    values = [float(value) for value in (text or "").split()]
    values.extend([0.0] * (6 - len(values)))
    return Pose(values[0], values[1], values[2], values[5])


def compose(parent: Pose, child: Pose) -> Pose:
    cosine = math.cos(parent.yaw)
    sine = math.sin(parent.yaw)
    return Pose(
        parent.x + cosine * child.x - sine * child.y,
        parent.y + sine * child.x + cosine * child.y,
        parent.z + child.z,
        parent.yaw + child.yaw,
    )


def projected_bounds(pose: Pose, size_x: float, size_y: float) -> tuple[float, ...]:
    half_x = size_x / 2.0
    half_y = size_y / 2.0
    cosine = abs(math.cos(pose.yaw))
    sine = abs(math.sin(pose.yaw))
    extent_x = cosine * half_x + sine * half_y
    extent_y = sine * half_x + cosine * half_y
    return pose.x - extent_x, pose.x + extent_x, pose.y - extent_y, pose.y + extent_y


def collision_bounds(model: ET.Element, model_pose: Pose):
    for link in model.findall("link"):
        link_pose = compose(model_pose, parse_pose(link.findtext("pose")))
        for collision in link.findall("collision"):
            box = collision.find("geometry/box/size")
            if box is None or not box.text:
                continue
            size_x, size_y, size_z = (float(value) for value in box.text.split())
            pose = compose(link_pose, parse_pose(collision.findtext("pose")))
            if pose.z - size_z / 2.0 <= SCAN_HEIGHT <= pose.z + size_z / 2.0:
                yield projected_bounds(pose, size_x, size_y)


def scene_bounds(world_file: Path):
    world = ET.parse(world_file).getroot().find("world")
    if world is None:
        raise ValueError(f"No <world> in {world_file}")

    for model in world.findall("model"):
        name = model.get("name", "")
        if name == "floor" or model.findtext("static") != "true":
            continue
        yield from collision_bounds(model, parse_pose(model.findtext("pose")))

    model_root = world_file.parent.parent / "models"
    for include in world.findall("include"):
        name = include.findtext("name", "")
        uri = include.findtext("uri", "")
        if not name.startswith("machine_") or not uri.startswith("model://"):
            continue
        included_file = model_root / uri.removeprefix("model://") / "model.sdf"
        included_model = ET.parse(included_file).getroot().find("model")
        if included_model is None:
            raise ValueError(f"No <model> in {included_file}")
        yield from collision_bounds(included_model, parse_pose(include.findtext("pose")))


def render_map(world_file: Path) -> str:
    grid = [[FREE for _ in range(WIDTH)] for _ in range(HEIGHT)]
    for min_x, max_x, min_y, max_y in scene_bounds(world_file):
        first_x = max(0, math.floor((min_x - ORIGIN_X) / RESOLUTION))
        last_x = min(WIDTH - 1, math.ceil((max_x - ORIGIN_X) / RESOLUTION) - 1)
        first_y = max(0, math.floor((min_y - ORIGIN_Y) / RESOLUTION))
        last_y = min(HEIGHT - 1, math.ceil((max_y - ORIGIN_Y) / RESOLUTION) - 1)
        for map_y in range(first_y, last_y + 1):
            image_y = HEIGHT - 1 - map_y
            for map_x in range(first_x, last_x + 1):
                grid[image_y][map_x] = OCCUPIED

    header = [
        "P2",
        "# Generated by scripts/generate_factory_map.py from Gazebo collisions.",
        f"{WIDTH} {HEIGHT}",
        "255",
    ]
    rows = [" ".join(str(cell) for cell in row) for row in grid]
    return "\n".join(header + rows) + "\n"


def main() -> int:
    project_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="fail if the committed map is stale"
    )
    args = parser.parse_args()
    world_file = (
        project_root
        / "src/mobile_manipulator_description/worlds/factory.sdf"
    )
    output_file = project_root / "src/factory_bringup/maps/factory_map.pgm"
    generated = render_map(world_file)
    if args.check:
        if output_file.read_text(encoding="ascii") != generated:
            print("factory_map.pgm is stale; run scripts/generate_factory_map.py")
            return 1
        print("factory_map.pgm matches Gazebo collision geometry")
        return 0
    output_file.write_text(generated, encoding="ascii")
    print(f"Wrote {output_file} ({WIDTH}x{HEIGHT}, {RESOLUTION:.2f} m/cell)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
